[package]
name = "scarlet-queen-entrypoint"
version.workspace = true
edition.workspace = true

[dependencies]
scarlet-queen-core = { path = "../scarlet-queen-core" }
scarlet-queen-generation = { path = "../scarlet-queen-generation" }
scarlet-queen-initializer = { path = "../scarlet-queen-initializer" }
plotters.workspace = true
rand.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true