[workspace]
resolver = "2"
members = [
  "crates/scarlet-queen-core",
  "crates/scarlet-queen-entrypoint",
  "crates/scarlet-queen-fitness",
  "crates/scarlet-queen-generation",
  "crates/scarlet-queen-replenisher",
  "crates/scarlet-queen-initializer",
  "crates/scarlet-queen-selector",
  "crates/pokemon",
]

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
rand = "0.10.0"
thiserror = "2.0.12"
plotters = "0.3.1"

serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.114"
