[workspace]
resolver = "2"
members = [ "crates/core","crates/entrypoint", "crates/fitness", "crates/generation", "crates/replenisher", "crates/initializer", "crates/selector"]

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
