[package]
name = "pokemon"
version.workspace = true
edition.workspace = true

[dependencies]
scarlet-queen-core = { path = "../scarlet-queen-core" }
scarlet-queen-entrypoint = { path = "../scarlet-queen-entrypoint" }
rand.workspace = true
plotters.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_derive.workspace = true