//! Mod for `InitializerTrait` and `GroupTrait`

use std::{fmt::Debug, io::Write};

use crate::individual::Individual;

/// A trait for initializing the group.
/// * `T` - A data generated by this.(A element of the group)
/// * `N` - The number of datas generated by this.(The number of the elements of the group)
pub trait InitializerTrait<T, const N: usize>
where
    T: Clone
{
    /// Generate an initalized array.
    fn initialize() -> [T; N];

    /// Initialize the group.
    /// * `G` - group
    /// * `R` - The `R` of group
    fn init_group<G, const R: usize>() -> G
    where
        G: GroupTrait<T, N, R>
    {
        G::new(Self::initialize())
    }
}

/// A trait for a group which contains individuals.
/// * `T` - A element of this group
/// * `N` - The number of individuals
/// * `R` - The number of individuals after individuals are reduced by selector
pub trait GroupTrait<T, const N: usize, const R: usize>
where
    T: Clone,
    Self: Sized,
{
    /// An error of cycle
    type Err: Debug;

    /// Create `Self` from a array.
    /// * `data` - A array of individuals
    fn new(data: [T; N]) -> Self;

    /// Run one cycle and update individuals.
    fn one_cycle(&mut self) -> Result<(), Self::Err>;

    /// Create an iterator of indivuduals.
    /// * `'a` - A lifetime of `self`.
    fn iter<'a>(&'a self) -> impl Iterator<Item = &'a Individual<T>>
    where
        T: 'a;

    /// Initialize `Self` by `I` algorithm.
    /// * `I` - Algorithm of initializing.
    fn init<I>() -> Self
    where
        I: InitializerTrait<T, N>,
    {
        I::init_group::<Self, R>()
    }

    /// Assign a number to individuals in order.
    fn reset_id(&self) {
        self.iter().enumerate().for_each(|(i, v)| v.set_id(i));
    }

    #[allow(unused_variables)]
    /// Run one cycle with outputing and update individuals.
    ///
    /// By default, there is not outputing.(Run `one_cycle` simply.)
    /// * `out` - A target of outputing.
    fn one_cycle_out<W>(&mut self, out: W) -> Result<(), Self::Err>
    where
        W: Write,
    {
        <Self as GroupTrait<T, N, R>>::one_cycle(self)
    }

    /// Clone individuals which are contained by this.
    fn clone_values(&self) -> Vec<T> {
        self.iter().map(|v| v.get_value()).cloned().collect::<Vec<T>>()
    }
}
