//! Mod for `InitializerTrait`.

/// A trait for initializing the group.
/// * `T` - A data generated by this.(An element of the group)
/// * `N` - The number of datas generated by this.(The number of the elements of the group)
///
/// # Example
/// ```
/// use scarlet_queen_core::InitializerTrait;
///
/// struct Initializer {}
/// impl<const N: usize> InitializerTrait<u8, N> for Initializer {
///     fn initialize() -> [u8; N] {
///         let mut i: u8 = 0;
///         [0; N].map(|_| {
///             i += 1;
///             i - 1
///         })
///     }
/// }
///
/// let array = <Initializer as InitializerTrait<u8, 10>>::initialize();
/// assert_eq!(array, [0u8, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
/// ```
pub trait InitializerTrait<T, const N: usize> {
    /// Generate an initalized array.
    fn initialize() -> [T; N];
}