name: dev-test

on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["dev", "feat/*", "fix/*", "chore/*", "update/*"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - scarlet-queen-core
          - scarlet-queen-entrypoint
          - scarlet-queen-fitness
          - scarlet-queen-generation
          - scarlet-queen-initializer
          - scarlet-queen-replenisher
          - scarlet-queen-selector
    name: ${{ matrix.crate }}-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build Check (${{ matrix.crate }})
        run: nix develop --command bash -c "cargo build --release --verbose -p ${{ matrix.crate }}"
      - name: Test (${{ matrix.crate }})
        run: nix develop --command bash -c "cargo test --verbose -p ${{ matrix.crate }}"
      - name: Lint (${{ matrix.crate }})
        run: nix develop --command bash -c "cargo clippy -p ${{ matrix.crate }} --all-targets --all-features"
