name: docs

on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Build mdbook
      - name: Build mdbook
        run: nix develop --command bash -c "mdbook build ./docs"
      # Add _config.yaml
      - name: Add _config.yaml
        run: |
          cp ./docs/_config.yaml ./docs/book/
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
      # Build rustdoc
      - name: Build rustdoc
        run: nix develop --command bash -c "cargo doc --no-deps --workspace"
      # Add rustdoc
      - name: Add rustdoc
        run: |
          cp -pR ./target/doc ./netlify
      # Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: './netlify'
          production-branch: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
