name: docs

on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Build mdbook
      - name: Build mdbook
        run: nix develop --command bash -c "mdbook build ./docs"
      # Add _config.yaml
      - name: Add _config.yaml
        run: |
          cp ./docs/_config.yaml ./docs/book/
      # Build rustdoc
      - name: Build rustdoc
        run: nix develop --command bash -c "cargo doc --no-deps --workspace"
      # Add rustdoc to book
      - name: Add rustdoc
        run: |
          cp -r ./target/doc/scarlet_queen_core ./docs/book/
          cp -r ./target/doc/scarlet_queen_entrypoint ./docs/book/
          cp -r ./target/doc/scarlet_queen_fitness ./docs/book/
          cp -r ./target/doc/scarlet_queen_generation ./docs/book/
          cp -r ./target/doc/scarlet_queen_initializer ./docs/book/
          cp -r ./target/doc/scarlet_queen_replenisher ./docs/book/
          cp -r ./target/doc/scarlet_queen_selector ./docs/book/
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
